import xml.etree.ElementTree as ET


def parse_nmap(xml_file):
    """
    Parse the XML report generated by Nmap and return
    a structured Python dictionary.
    """

    tree = ET.parse(xml_file)

    root = tree.getroot()

    report = {}

    host = root.find("host")

    # -----------------------------
    # Target IP
    # -----------------------------
    address = host.find("address")

    report["ip"] = address.attrib["addr"]

    # -----------------------------
    # Ports
    # -----------------------------
    ports = []

    for port in host.findall("ports/port"):

        state = port.find("state")

        if state.attrib["state"] != "open":
            continue

        service = port.find("service")

        ports.append({

            "port": port.attrib["portid"],

            "protocol": port.attrib["protocol"],

            "service": service.attrib.get("name", ""),

            "product": service.attrib.get("product", ""),

            "version": service.attrib.get("version", "")

        })

    # -----------------------------
    # Operating System Detection
    # -----------------------------
    osmatch = host.find("os/osmatch")

    if osmatch is not None:
        report["os"] = osmatch.attrib.get("name", "Unknown")
    else:
        report["os"] = "Unknown"

    # -----------------------------
    # Save Port Information
    # -----------------------------
    report["ports"] = ports

    return report
