from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import os

def generate_pdf(report):
    os.makedirs("reports", exist_ok=True)

    filename = "reports/ReconX_Report.pdf"
    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()
    content = []

    # Title
    content.append(
        Paragraph(
            "ReconX Professional Security Assessment Report",
            styles["Title"]
        )
    )
    content.append(Spacer(1, 20))

    # Target
    content.append(
        Paragraph(
            f"Target: {report.get('ip','Unknown')}",
            styles["Normal"]
        )
    )
    content.append(Spacer(1, 20))

    # Executive Summary
    content.append(
        Paragraph(
            "Executive Summary",
            styles["Heading2"]
        )
    )

    risk = report.get("risk", {})
    summary = f"""
    ReconX performed an automated security assessment.

    Overall Risk Level: {risk.get('severity','Unknown')}
    Risk Score: {risk.get('score',0)}
    High Findings: {risk.get('high',0)}
    Medium Findings: {risk.get('medium',0)}
    Low Findings: {risk.get('low',0)}
    Informational Findings: {risk.get('info',0)}
    """

    content.append(
        Paragraph(summary.replace("\n", "<br/>"), styles["Normal"])
    )
    content.append(Spacer(1, 15))

    # OS Information
    content.append(
        Paragraph(
            f"Operating System: {report.get('os','Unknown')}",
            styles["Normal"]
        )
    )
    content.append(Spacer(1, 20))

    # Ports
    content.append(
        Paragraph("Open Ports and Services", styles["Heading2"])
    )
    for port in report.get("ports", []):
        data = (
            f"Port: {port.get('port')} | "
            f"Protocol: {port.get('protocol')} | "
            f"Service: {port.get('service')} | "
            f"Version: {port.get('version','Unknown')}"
        )
        content.append(Paragraph(data, styles["Normal"]))
    content.append(Spacer(1, 20))

    # Vulnerabilities
    content.append(
        Paragraph("Vulnerability Findings", styles["Heading2"])
    )

    vulnerabilities = report.get("vulnerabilities", [])
    if vulnerabilities:
        for vuln in vulnerabilities:
            finding = f"""
            CVE: {vuln.get('cve','N/A')}<br/>
            Service: {vuln.get('service','Unknown')}<br/>
            Severity: {vuln.get('severity','Unknown')}<br/>
            CVSS Score: {vuln.get('cvss','N/A')}<br/>
            Description: {vuln.get('description','No description')}<br/>
            Recommendation: Update affected software and apply security patches.
            """
            content.append(Paragraph(finding, styles["Normal"]))
            content.append(Spacer(1, 15))
    else:
        content.append(
            Paragraph("No vulnerabilities detected.", styles["Normal"])
        )

    content.append(Spacer(1, 20))

    # Footer
    content.append(
        Paragraph(
            "Generated by ReconX Automated Reconnaissance Framework",
            styles["Italic"]
        )
    )
    content.append(Spacer(1, 20))

    # Security Recommendations
    content.append(
        Paragraph("Security Recommendations", styles["Heading2"])
    )
    recommendations = [
        "Remove unnecessary open services.",
        "Update outdated software versions.",
        "Use secure encrypted protocols.",
        "Apply security patches regularly.",
        "Perform continuous vulnerability monitoring."
    ]
    for item in recommendations:
        content.append(Paragraph("• " + item, styles["Normal"]))

    # Build PDF
    doc.build(content)
    return filename

